title: "Blog"
author: "Zilu Ma"
description: "Learning notes"
theme: minima

url: "https://ziluma.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
plugins:
  - jekyll-feed
  - jekyll-seo-tag

